# Generated by Django 3.2.25 on 2026-05-29 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('stored_path', models.CharField(max_length=500, verbose_name='存储路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_imported', models.BooleanField(default=False, verbose_name='是否已导入')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='上传用户')),
            ],
            options={
                'verbose_name': '文件上传',
                'verbose_name_plural': '文件上传',
                'db_table': 'core_file_upload',
                'ordering': ['-created_at'],
            },
        ),
    ]
