# Generated by Django 3.2.25 on 2026-06-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_externallink_dashboardcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='chart_type',
            field=models.CharField(choices=[('bar', '柱状图'), ('line', '折线图'), ('pie', '饼图'), ('doughnut', '环形图'), ('horizontal_bar', '横向柱状图')], default='bar', max_length=20, verbose_name='图表类型'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='x_axis_field',
            field=models.CharField(blank=True, help_text='SQL查询结果中的列名，用作X轴或饼图标签', max_length=100, verbose_name='X轴/标签字段'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='y_axis_field',
            field=models.CharField(blank=True, help_text='SQL查询结果中的列名，用作Y轴或饼图数值', max_length=100, verbose_name='Y轴/数值字段'),
        ),
    ]
