# Generated by Django 3.2.25 on 2026-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260623_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='y_axis_field',
            field=models.TextField(blank=True, help_text='SQL查询结果中的列名，支持逗号分隔多个字段，如：本金,利息。饼图只取第一个字段', verbose_name='Y轴/数值字段'),
        ),
    ]
