# Generated by Django 3.2.25 on 2026-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dashboardcard_y_axis_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardcard',
            name='x_axis_field',
            field=models.TextField(blank=True, help_text='SQL查询结果中的列名，支持逗号分隔多个字段（多个字段会拼接为标签），如：渠道类型,公司名称', verbose_name='X轴/标签字段'),
        ),
    ]
