# Generated by Django 3.2.25 on 2026-06-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_dashboardcard_x_axis_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='chart_sort_dir',
            field=models.CharField(choices=[('none', '不排序'), ('ASC', '升序'), ('DESC', '降序')], default='none', max_length=10, verbose_name='排序方向'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='group_by_field',
            field=models.CharField(blank=True, help_text='按该字段分组生成多条数据系列，如：资金方。留空则不分组', max_length=100, verbose_name='维度字段'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='show_data_label',
            field=models.BooleanField(default=False, help_text='在图表上显示具体数值', verbose_name='显示数值标签'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='sort_field',
            field=models.CharField(blank=True, help_text='按该字段排序，留空则按数据原始顺序', max_length=100, verbose_name='排序字段'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='stacked',
            field=models.BooleanField(default=False, help_text='柱状图/折线图是否堆叠显示', verbose_name='堆叠模式'),
        ),
    ]
