# Generated by Django 3.2.25 on 2026-06-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20260624_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='chart_height',
            field=models.IntegerField(default=300, help_text='图表显示高度，默认300px', verbose_name='图表高度(px)'),
        ),
        migrations.AlterField(
            model_name='dashboardcard',
            name='chart_type',
            field=models.CharField(choices=[('bar', '柱状图'), ('line', '折线图'), ('area', '面积图'), ('pie', '饼图'), ('doughnut', '环形图'), ('horizontal_bar', '横向柱状图')], default='bar', max_length=20, verbose_name='图表类型'),
        ),
    ]
