# Generated by Django 3.2.25 on 2026-06-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20260624_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardcard',
            name='color_scheme',
            field=models.CharField(choices=[('default', '经典蓝'), ('business', '商务灰'), ('vibrant', '活力彩'), ('morandi', '莫兰迪'), ('earth', '大地色'), ('mint', '薄荷清新'), ('custom', '自定义')], default='default', help_text='选择图表配色方案', max_length=50, verbose_name='配色方案'),
        ),
        migrations.AddField(
            model_name='dashboardcard',
            name='custom_colors',
            field=models.TextField(blank=True, help_text='当配色方案选择"自定义"时，输入逗号分隔的HEX颜色值，如：#3b82f6,#ef4444,#10b981', verbose_name='自定义颜色'),
        ),
    ]
