# Generated by Django 3.2.25 on 2026-05-29 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='脚本名称')),
                ('description', models.TextField(blank=True, verbose_name='脚本说明')),
                ('file', models.FileField(blank=True, null=True, upload_to='scripts/', verbose_name='SQL文件')),
                ('content', models.TextField(blank=True, help_text='可以直接粘贴 SQL，或上传文件', verbose_name='脚本内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('timeout', models.IntegerField(default=300, verbose_name='执行超时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'SQL脚本',
                'verbose_name_plural': 'SQL脚本',
                'db_table': 'sql_scripts_script',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('manual', '手动执行'), ('scheduled', '定时执行')], default='manual', max_length=20, verbose_name='触发类型')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='执行状态')),
                ('output', models.TextField(blank=True, verbose_name='执行结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行耗时(秒)')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='影响行数')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sql_scripts.sqlscript', verbose_name='脚本')),
            ],
            options={
                'verbose_name': '执行日志',
                'verbose_name_plural': '执行日志',
                'db_table': 'sql_scripts_log',
                'ordering': ['-executed_at'],
            },
        ),
    ]
