# Generated by Django 3.2.25 on 2026-05-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_scripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='连接名称')),
                ('host', models.CharField(max_length=200, verbose_name='主机')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('database', models.CharField(max_length=100, verbose_name='数据库名')),
                ('charset', models.CharField(default='utf8mb4', max_length=20, verbose_name='字符集')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '数据库连接',
                'verbose_name_plural': '数据库连接',
                'db_table': 'sql_scripts_db_connection',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='sqlscript',
            name='target_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scripts', to='sql_scripts.dbconnection', verbose_name='目标数据库'),
        ),
    ]
