# Generated by Django 3.2.25 on 2026-05-29 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='需求标题')),
                ('description', models.TextField(blank=True, verbose_name='需求描述')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='期望完成日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests', to=settings.AUTH_USER_MODEL, verbose_name='提出人')),
            ],
            options={
                'verbose_name': '报表需求',
                'verbose_name_plural': '报表需求',
                'db_table': 'reports_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reports.reportrequest', verbose_name='需求')),
            ],
            options={
                'verbose_name': '需求评论',
                'verbose_name_plural': '需求评论',
                'db_table': 'reports_comment',
                'ordering': ['created_at'],
            },
        ),
    ]
