# Generated by Django 3.2.25 on 2026-05-29 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportrequest',
            name='assignee',
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL, verbose_name='开发人员'),
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='requester',
            field=models.CharField(blank=True, default='', help_text='需求提出人姓名', max_length=100, verbose_name='提出人'),
        ),
    ]
