# Generated by Django 3.2.25 on 2026-06-02 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sql_scripts', '0002_auto_20260529_1429'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='规则描述')),
                ('sql_query', models.TextField(help_text='输入要执行的 SQL 查询', verbose_name='SQL 查询')),
                ('condition_type', models.CharField(choices=[('rows_gt_0', '查询返回行数 > 0（存在异常时告警）'), ('rows_eq_0', '查询返回行数 = 0（数据缺失时告警）'), ('value_gt', '某列值 > 阈值'), ('value_lt', '某列值 < 阈值'), ('value_eq', '某列值 = 阈值')], default='rows_gt_0', max_length=20, verbose_name='条件类型')),
                ('check_column', models.CharField(blank=True, help_text='条件为列值比较时必填', max_length=100, verbose_name='检查列名')),
                ('threshold', models.FloatField(blank=True, default=0, verbose_name='阈值')),
                ('schedule_type', models.CharField(choices=[('manual', '仅手动执行'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='调度类型')),
                ('schedule_hour', models.IntegerField(default=8, verbose_name='执行小时')),
                ('schedule_minute', models.IntegerField(default=0, verbose_name='执行分钟')),
                ('schedule_days', models.CharField(blank=True, help_text='逗号分隔的数字，0=周一 6=周日', max_length=50, verbose_name='周几执行')),
                ('schedule_day_of_month', models.IntegerField(default=1, verbose_name='每月几号')),
                ('notify_channel', models.CharField(choices=[('none', '不通知'), ('dingtalk', '钉钉'), ('wecom', '企业微信'), ('email', '邮件')], default='none', max_length=20, verbose_name='通知渠道')),
                ('email_recipients', models.TextField(blank=True, help_text='多个邮箱用逗号分隔', verbose_name='收件人邮箱')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_check_at', models.DateTimeField(blank=True, null=True, verbose_name='上次检查时间')),
                ('last_check_status', models.CharField(blank=True, choices=[('normal', '正常'), ('alert', '告警'), ('error', '错误'), ('pending', '未执行')], default='pending', max_length=20, verbose_name='上次状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('target_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_rules', to='sql_scripts.dbconnection', verbose_name='目标数据库')),
            ],
            options={
                'verbose_name': '质量规则',
                'verbose_name_plural': '质量规则',
                'db_table': 'data_quality_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QualityCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('normal', '正常'), ('alert', '告警'), ('error', '错误')], max_length=20, verbose_name='结果状态')),
                ('result_value', models.TextField(blank=True, verbose_name='查询结果摘要')),
                ('alert_message', models.TextField(blank=True, verbose_name='告警消息')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('duration', models.FloatField(default=0, verbose_name='执行耗时(秒)')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('triggered_by', models.CharField(choices=[('manual', '手动'), ('scheduled', '定时')], default='manual', max_length=20, verbose_name='触发方式')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='data_quality.qualityrule', verbose_name='规则')),
            ],
            options={
                'verbose_name': '检查日志',
                'verbose_name_plural': '检查日志',
                'db_table': 'data_quality_check_log',
                'ordering': ['-executed_at'],
            },
        ),
    ]
