# Generated by Django 3.2.25 on 2026-06-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityrule',
            name='interval_minutes',
            field=models.IntegerField(default=5, help_text='每N分钟执行一次，范围1-1440', verbose_name='执行间隔(分钟)'),
        ),
        migrations.AlterField(
            model_name='qualityrule',
            name='schedule_type',
            field=models.CharField(choices=[('manual', '仅手动执行'), ('every_minutes', '每N分钟'), ('daily', '每天'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='调度类型'),
        ),
    ]
