# Generated by Django 3.2.25 on 2026-05-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('dingtalk', '钉钉'), ('wecom', '企业微信')], max_length=20, unique=True, verbose_name='通知渠道')),
                ('webhook_url', models.URLField(max_length=500, verbose_name='Webhook URL')),
                ('secret', models.CharField(blank=True, help_text='钉钉加签密钥（可选）', max_length=200, verbose_name='加签密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知配置',
                'verbose_name_plural': '通知配置',
                'db_table': 'notifications_config',
            },
        ),
    ]
