# Generated by Django 3.2.25 on 2026-06-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationconfig',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.qq.com', max_length=200, verbose_name='SMTP 服务器'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='邮箱密码/授权码'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=200, verbose_name='发件人邮箱'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='email_port',
            field=models.IntegerField(default=465, verbose_name='SMTP 端口'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='email_recipients',
            field=models.TextField(blank=True, help_text='多个邮箱用逗号分隔', verbose_name='收件人邮箱'),
        ),
        migrations.AddField(
            model_name='notificationconfig',
            name='email_use_ssl',
            field=models.BooleanField(default=True, verbose_name='使用 SSL'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='channel',
            field=models.CharField(choices=[('dingtalk', '钉钉'), ('wecom', '企业微信'), ('email', '邮件')], max_length=20, unique=True, verbose_name='通知渠道'),
        ),
    ]
