# Generated by Django 3.2.25 on 2026-06-03 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sql_scripts', '0002_auto_20260529_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineageScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True, verbose_name='扫描时间')),
                ('event_count', models.IntegerField(default=0, verbose_name='事件数')),
                ('table_count', models.IntegerField(default=0, verbose_name='表数')),
                ('edge_count', models.IntegerField(default=0, verbose_name='依赖关系数')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('source_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineage_scans', to='sql_scripts.dbconnection', verbose_name='数据库连接')),
            ],
            options={
                'verbose_name': '扫描记录',
                'verbose_name_plural': '扫描记录',
                'db_table': 'data_lineage_scan',
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='LineageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=200, verbose_name='表名')),
                ('database_name', models.CharField(blank=True, max_length=200, verbose_name='所属数据库')),
                ('table_comment', models.TextField(blank=True, verbose_name='表注释')),
                ('columns_json', models.TextField(blank=True, help_text='JSON 格式的字段信息：[{"name":"col","type":"int","comment":"注释"}]', verbose_name='字段列表(JSON)')),
                ('is_source', models.BooleanField(default=False, help_text='基础表来自源库(A)，中间表来自开发库(B)', verbose_name='是否为基础表')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='data_lineage.lineagescan', verbose_name='扫描记录')),
            ],
            options={
                'verbose_name': '血缘表',
                'verbose_name_plural': '血缘表',
                'db_table': 'data_lineage_table',
                'ordering': ['table_name'],
            },
        ),
        migrations.CreateModel(
            name='LineageEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_table', models.CharField(max_length=200, verbose_name='源表名')),
                ('source_database', models.CharField(blank=True, max_length=200, verbose_name='源表数据库')),
                ('target_table', models.CharField(max_length=200, verbose_name='目标表名')),
                ('target_database', models.CharField(blank=True, max_length=200, verbose_name='目标表数据库')),
                ('event_name', models.CharField(blank=True, max_length=200, verbose_name='事件名')),
                ('event_sql', models.TextField(blank=True, verbose_name='事件SQL')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='data_lineage.lineagescan', verbose_name='扫描记录')),
            ],
            options={
                'verbose_name': '血缘关系',
                'verbose_name_plural': '血缘关系',
                'db_table': 'data_lineage_edge',
            },
        ),
    ]
