# Generated by Django 3.2.25 on 2026-05-29 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sql_scripts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('cron_expr', models.CharField(help_text='如: 0 8 * * 1 (每周一8点)', max_length=100, verbose_name='Cron 表达式')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('notify_channel', models.CharField(choices=[('none', '不通知'), ('dingtalk', '钉钉'), ('wecom', '企业微信')], default='none', max_length=20, verbose_name='通知渠道')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('last_status', models.CharField(blank=True, max_length=20, verbose_name='上次状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_tasks', to='sql_scripts.sqlscript', verbose_name='脚本')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'db_table': 'scheduler_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
