# Generated by Django 3.2.25 on 2026-05-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='schedule_day_of_month',
            field=models.IntegerField(default=1, verbose_name='每月几号'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='schedule_days',
            field=models.CharField(blank=True, help_text='逗号分隔的数字，0=周一 6=周日', max_length=50, verbose_name='周几执行'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='schedule_hour',
            field=models.IntegerField(default=8, verbose_name='执行小时'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='schedule_minute',
            field=models.IntegerField(default=0, verbose_name='执行分钟'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='schedule_type',
            field=models.CharField(choices=[('daily', '每天'), ('weekly', '每周'), ('monthly', '每月'), ('custom', '自定义')], default='daily', max_length=20, verbose_name='调度类型'),
        ),
        migrations.AlterField(
            model_name='scheduledtask',
            name='cron_expr',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cron 表达式（自动生成）'),
        ),
    ]
