# Generated by Django 3.2.25 on 2026-06-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20260529_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtask',
            name='notify_channel',
            field=models.CharField(choices=[('none', '不通知'), ('dingtalk', '钉钉'), ('wecom', '企业微信'), ('email', '邮件')], default='none', max_length=20, verbose_name='通知渠道'),
        ),
    ]
