# Generated by Django 3.2.25 on 2026-06-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_alter_scheduledtask_notify_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtask',
            name='email_recipients',
            field=models.TextField(blank=True, help_text='多个邮箱用逗号分隔，用于发送执行结果文件', verbose_name='收件人邮箱'),
        ),
    ]
