# Generated by Django 3.2.25 on 2026-06-17 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0004_scheduledtask_email_recipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称快照')),
                ('script_name', models.CharField(blank=True, max_length=200, verbose_name='脚本名称快照')),
                ('sql_executed', models.TextField(blank=True, verbose_name='执行的SQL')),
                ('trigger_type', models.CharField(choices=[('manual', '手动执行'), ('scheduled', '定时执行'), ('send_file', '发送文件')], default='manual', max_length=20, verbose_name='触发方式')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], default='success', max_length=20, verbose_name='执行状态')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='影响行数')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='执行耗时(秒)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('notify_channel', models.CharField(blank=True, max_length=20, verbose_name='通知渠道')),
                ('notify_target', models.TextField(blank=True, help_text='邮箱地址等', verbose_name='通知对象')),
                ('notify_status', models.BooleanField(blank=True, null=True, verbose_name='通知是否成功')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='scheduler.scheduledtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'db_table': 'scheduler_task_log',
                'ordering': ['-executed_at'],
            },
        ),
    ]
